name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: mongodb://localhost:42069/suryia
    strategy:
      matrix:
        node-version: [18.17]
        mongodb-version: ['7.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: test-rs
        mongodb-port: 42069

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install

    - name: Initialize Database
      run: |
        cd backend 
        node initialize.ts 

    - name: Build Backend
      run: |
        cd backend
        npm run build
    
    - name: Start API
      run: |
        cd backend
        npm start

