name: Full Stack Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

# Backend-Tests
    - name: Install Backend Dependencies
      run: 
        cd backend
        npm install

    - name: Build Backend
      run: 
        cd backend
        npm run build
   
    - name: Start Backend
      run: 
        cd backend
        npm run start
